// Code generated from i18n-catalog/en.json during the 2026-07 i18n migration. DO NOT EDIT.

package notifyrender

// BaselineEN is the compiled-in en fallback catalog (spec D1): dotted
// "<section>.title"/"<section>.body" keys for all catalog sections. It is the
// source of truth the overlay engine layers per-locale translations over.
var BaselineEN = map[string]string{
	"admin_transfer_accepted.title":       "Admin transfer accepted",
	"admin_transfer_accepted.body":        "{{.to_user_name}} accepted the admin role of {{.organization_name}}.",
	"admin_transfer_cancelled.title":      "Admin transfer cancelled",
	"admin_transfer_cancelled.body":       "{{.from_user_name}} cancelled the admin transfer for {{.organization_name}}.",
	"admin_transfer_expired.title":        "Admin transfer expired",
	"admin_transfer_expired.body":         "The admin transfer for {{.organization_name}} with {{.counterparty_name}} expired without action.",
	"admin_transfer_initiated.title":      "Admin role transfer offer",
	"admin_transfer_initiated.body":       "{{.from_user_name}} wants to transfer the admin role of {{.organization_name}} to you. Respond before the offer expires.",
	"admin_transfer_rejected.title":       "Admin transfer declined",
	"admin_transfer_rejected.body":        "{{.to_user_name}} declined the admin transfer for {{.organization_name}}.",
	"admin_transferred_new.title":         "You are now the team admin",
	"admin_transferred_new.body":          "You have been made the admin of {{.team_name}}.",
	"admin_transferred_old.title":         "Team admin transferred",
	"admin_transferred_old.body":          "You transferred admin rights for {{.team_name}}.",
	"chat_message.title":                  "New message from {{.sender_name}}",
	"chat_message.body":                   "{{.preview}}",
	"favorite_listing_removed.title":      "Favorite listing removed",
	"favorite_listing_removed.body":       "'{{.listing_title}}' is no longer available.",
	"favorite_price_changed.title":        "Price changed",
	"favorite_price_changed.body":         "The price of '{{.listing_title}}' changed from {{.old_price}} to {{.new_price}} {{.currency}}.",
	"invite_accepted.title":               "Invitation accepted",
	"invite_accepted.body":                "{{.phone}} accepted your invitation to join as {{.role}}.",
	"invite_declined.title":               "Invitation declined",
	"invite_declined.body":                "{{.phone}} declined your invitation.",
	"listing_approved.title":              "Listing approved",
	"listing_approved.body":               "Your listing '{{.listing_title}}' is now live.",
	"listing_rejected.title":              "Listing rejected",
	"listing_rejected.body":               "Your listing '{{.listing_title}}' was rejected: {{.reason}}",
	"listing_unpublished.title":           "Listing unpublished",
	"listing_unpublished.body":            "Your listing '{{.listing_title}}' was unpublished: {{.reason}}",
	"member_blocked.title":                "Access temporarily restricted",
	"member_blocked.body":                 "Your access to the team {{.team_name}} has been temporarily restricted.",
	"member_removed.title":                "Removed from team",
	"member_removed.body":                 "You have been removed from the team {{.team_name}}.",
	"member_role_changed_manager.title":   "Your role has changed",
	"member_role_changed_manager.body":    "You are now a manager of the team {{.team_name}}.",
	"member_role_changed_operator.title":  "Your role has changed",
	"member_role_changed_operator.body":   "You are now an operator of the team {{.team_name}}.",
	"member_unblocked.title":              "Access restored",
	"member_unblocked.body":               "Your access to the team {{.team_name}} has been restored.",
	"operator_assigned.title":             "Operator assigned",
	"operator_assigned.body":              "{{.operator_name}} has been assigned.",
	"operator_released.title":             "Operator released",
	"operator_released.body":              "{{.operator_name}} has been released.",
	"order_auto_cancelled.title":          "Order cancelled",
	"order_auto_cancelled.body":           "The order for '{{.listing_title}}' was cancelled automatically after 14 days of inactivity.",
	"order_auto_completed.title":          "Order completed",
	"order_auto_completed.body":           "The order for '{{.listing_title}}' was completed automatically.",
	"order_cancelled.title":               "Order cancelled",
	"order_cancelled.body":                "The order for '{{.listing_title}}' was cancelled by {{.cancelled_by}}.",
	"order_confirmed.title":               "Order confirmed",
	"order_confirmed.body":                "The order for '{{.listing_title}}' is confirmed.",
	"order_counter_offer_sent.title":      "Counter-offer received",
	"order_counter_offer_sent.body":       "The owner proposed new terms for '{{.listing_title}}'.",
	"order_counter_offer_withdrawn.title": "Counter-offer withdrawn",
	"order_counter_offer_withdrawn.body":  "The owner withdrew the counter-offer for '{{.listing_title}}'.",
	"order_receipt_confirmed.title":       "Receipt confirmed",
	"order_receipt_confirmed.body":        "The renter confirmed receipt of '{{.listing_title}}'.",
	"order_request_accepted.title":        "Request accepted",
	"order_request_accepted.body":         "The owner is reviewing your request for '{{.listing_title}}'.",
	"order_request_created.title":         "New rental request",
	"order_request_created.body":          "You have a new rental request for '{{.listing_title}}'.",
	"order_review_window_ending.title":    "Review window closing",
	"order_review_window_ending.body":     "Your review window for '{{.listing_title}}' ends in 2 days.",
	"order_terms_agreed.title":            "Terms agreed",
	"order_terms_agreed.body":             "The owner agreed terms for '{{.listing_title}}'. Confirm the order.",
	"order_transferred.title":             "Equipment handed over",
	"order_transferred.body":              "'{{.listing_title}}' was handed over. Confirm receipt.",
	"team_invite_tenant_manager.title":    "Invitation to join {{.team_name}}",
	"team_invite_tenant_manager.body":     "{{.inviter_name}} invited you to join {{.team_name}} as a manager.",
	"team_invite_tenant_operator.title":   "Invitation to join {{.team_name}}",
	"team_invite_tenant_operator.body":    "{{.inviter_name}} invited you to join {{.team_name}} as an operator.",
	"team_invite_user_manager.title":      "Team invitation",
	"team_invite_user_manager.body":       "{{.inviter_name}} invited you to {{.team_name}} as a manager.",
	"team_invite_user_operator.title":     "Team invitation",
	"team_invite_user_operator.body":      "{{.inviter_name}} invited you to {{.team_name}} as an operator.",
	"team_member_left.title":              "{{.member_name}} left the team",
	"team_member_left.body":               "{{.member_name}} is no longer a member of the team {{.team_name}}.",
	"team_member_removed_admin.title":     "{{.removed_member_name}} was removed from the team",
	"team_member_removed_admin.body":      "{{.removed_member_name}} was removed from the team {{.team_name}}.",
	"tenant_rejected.title":               "Organization rejected",
	"tenant_rejected.body":                "Your organization was rejected: {{.reason}}",
	"tenant_verified.title":               "Organization verified",
	"tenant_verified.body":                "{{.organization_name}} has been verified.",
	"wallet_operation_decided.title":      "Wallet operation {{.decision}}",
	"wallet_operation_decided.body":       "Your wallet operation for {{.amount}} {{.currency}} was {{.decision}}.",
	"wallet_operation_requested.title":    "Wallet operation requested",
	"wallet_operation_requested.body":     "A {{.operation_kind}} of {{.amount}} {{.currency}} has been requested.",
}
