// Seeded from i18n-catalog/en.json during the 2026-07 i18n migration; since the
// #66 refactor (in-code notifyrender baseline, Tolgee sync dropped) this file is
// the hand-maintained en source of truth. Add a section here for every new
// catalog type — the overlay engine layers per-locale translations on top of it.

package notifyrender

// BaselineEN is the compiled-in en fallback catalog (spec D1): dotted
// "<section>.title"/"<section>.body" keys for all catalog sections. It is the
// source of truth the overlay engine layers per-locale translations over.
var BaselineEN = map[string]string{
	"chat_message.body":                         "{{.preview}}",
	"chat_message.title":                        "New message from {{.sender_name}}",
	"delivery_auto_confirmed.body":              "{{if .request_no}}Request #{{.request_no}}{{else}}The request{{end}} was auto-confirmed. You can leave a review within 14 days.",
	"delivery_auto_confirmed.title":             "Delivery auto-confirmed",
	"delivery_awaiting_receipt.body":            "The carrier confirmed delivery. Please confirm receipt of the equipment.",
	"delivery_awaiting_receipt.title":           "Confirm receipt",
	"delivery_cascade_cancelled.body":           "{{if .request_no}}Delivery request #{{.request_no}}{{else}}The delivery{{end}} was cancelled because the linked rental was cancelled.",
	"delivery_cascade_cancelled.title":          "Delivery cancelled",
	"delivery_counter_offer_accepted.body":      "The customer accepted your offer. Delivery terms are confirmed.",
	"delivery_counter_offer_accepted.title":     "Offer accepted",
	"delivery_counter_offer_declined.body":      "The customer declined your offer. The request returned to its original state.",
	"delivery_counter_offer_declined.title":     "Offer declined",
	"delivery_counter_offer_sent.body":          "The carrier proposed a changed delivery price. Review the offer.",
	"delivery_counter_offer_sent.title":         "New price offer",
	"delivery_counter_offer_withdrawn.body":     "The carrier withdrew their offer. The request returned to its original terms.",
	"delivery_counter_offer_withdrawn.title":    "Offer withdrawn",
	"delivery_in_transit.body":                  "In transit. The carrier picked up the equipment.",
	"delivery_in_transit.title":                 "In transit",
	"delivery_loading_today.body":               "Loading is today for your request{{if .request_no}} #{{.request_no}}{{end}} ({{.route}}).",
	"delivery_loading_today.title":              "Loading today",
	"delivery_receipt_reminder.body":            "Confirm receipt of the equipment{{if .request_no}} for request #{{.request_no}}{{end}} — without a response the request auto-confirms in 24 hours.",
	"delivery_receipt_reminder.title":           "Confirm receipt",
	"delivery_request_accepted.body":            "The carrier accepted your request. Final price: {{.final_price}} {{.currency}}.",
	"delivery_request_accepted.title":           "Request accepted",
	"delivery_request_cancelled.body":           "{{.cancelled_by}} cancelled {{if .request_no}}request #{{.request_no}}{{else}}the request{{end}}.",
	"delivery_request_cancelled.title":          "Request cancelled",
	"delivery_request_completed.body":           "The request is complete — receipt confirmed.",
	"delivery_request_completed.title":          "Request completed",
	"delivery_request_created.body":             "You have a new delivery request{{if .request_no}} #{{.request_no}}{{end}}. Review it.",
	"delivery_request_created.title":            "New delivery request",
	"delivery_request_expired.body":             "{{if .request_no}}Request #{{.request_no}}{{else}}The request{{end}} expired — the loading date has passed. You can repeat the request.",
	"delivery_request_expired.title":            "Request expired",
	"delivery_request_rejected.body":            "The carrier declined your request.",
	"delivery_request_rejected.title":           "Request declined",
	"delivery_review_invite.body":               "Rate the carrier{{if .request_no}} for request #{{.request_no}}{{end}} — you have 14 days.",
	"delivery_review_invite.title":              "Rate the carrier",
	"delivery_review_window_ending.body":        "Your review window{{if .request_no}} for request #{{.request_no}}{{end}} is closing — 2 days left.",
	"delivery_review_window_ending.title":       "Review window ending",
	"favorite_listing_removed.body":             "'{{.listing_title}}' is no longer available.",
	"favorite_listing_removed.title":            "Favorite listing removed",
	"favorite_price_changed.body":               "The price of '{{.listing_title}}' changed from {{.old_price}} to {{.new_price}} {{.currency}}.",
	"favorite_price_changed.title":              "Price changed",
	"invite_accepted.body":                      "{{.phone}} accepted your invitation to join as {{.role}}.",
	"invite_accepted.title":                     "Invitation accepted",
	"invite_declined.body":                      "{{.phone}} declined your invitation.",
	"invite_declined.title":                     "Invitation declined",
	"listing_approved.body":                     "Your listing '{{.listing_title}}' is now live.",
	"listing_approved.title":                    "Listing approved",
	"listing_rejected.body":                     "Your listing '{{.listing_title}}' was rejected: {{.reason}}",
	"listing_rejected.title":                    "Listing rejected",
	"listing_unpublished.body":                  "Your listing '{{.listing_title}}' was unpublished: {{.reason}}",
	"listing_unpublished.title":                 "Listing unpublished",
	"member_blocked.body":                       "Your access to the tenant {{.tenant_name}} has been temporarily restricted.",
	"member_blocked.title":                      "Access temporarily restricted",
	"member_removed.body":                       "You have been removed from the tenant {{.tenant_name}}.",
	"member_removed.title":                      "Removed from tenant",
	"member_role_changed_manager.body":          "You are now a manager of the tenant {{.tenant_name}}.",
	"member_role_changed_manager.title":         "Your role has changed",
	"member_role_changed_operator.body":         "You are now an operator of the tenant {{.tenant_name}}.",
	"member_role_changed_operator.title":        "Your role has changed",
	"member_unblocked.body":                     "Your access to the tenant {{.tenant_name}} has been restored.",
	"member_unblocked.title":                    "Access restored",
	"operator_assigned.body":                    "{{.operator_name}} has been assigned.",
	"operator_assigned.title":                   "Operator assigned",
	"operator_released.body":                    "{{.operator_name}} has been released.",
	"operator_released.title":                   "Operator released",
	"order_auto_cancelled.body":                 "The order for '{{.listing_title}}' was cancelled automatically after 14 days of inactivity.",
	"order_auto_cancelled.title":                "Order cancelled",
	"order_auto_completed.body":                 "The order for '{{.listing_title}}' was completed automatically.",
	"order_auto_completed.title":                "Order completed",
	"order_cancelled.body":                      "The order for '{{.listing_title}}' was cancelled by {{.cancelled_by}}.",
	"order_cancelled.title":                     "Order cancelled",
	"order_confirmed.body":                      "The order for '{{.listing_title}}' is confirmed.",
	"order_confirmed.title":                     "Order confirmed",
	"order_counter_offer_sent.body":             "The owner proposed new terms for '{{.listing_title}}'.",
	"order_counter_offer_sent.title":            "Counter-offer received",
	"order_counter_offer_withdrawn.body":        "The owner withdrew the counter-offer for '{{.listing_title}}'.",
	"order_counter_offer_withdrawn.title":       "Counter-offer withdrawn",
	"order_receipt_confirmed.body":              "The renter confirmed receipt of '{{.listing_title}}'.",
	"order_receipt_confirmed.title":             "Receipt confirmed",
	"order_request_accepted.body":               "The owner is reviewing your request for '{{.listing_title}}'.",
	"order_request_accepted.title":              "Request accepted",
	"order_request_created.body":                "You have a new rental request for '{{.listing_title}}'.",
	"order_request_created.title":               "New rental request",
	"order_review_window_ending.body":           "Your review window for '{{.listing_title}}' ends in 2 days.",
	"order_review_window_ending.title":          "Review window closing",
	"order_terms_agreed.body":                   "The owner agreed terms for '{{.listing_title}}'. Confirm the order.",
	"order_terms_agreed.title":                  "Terms agreed",
	"order_transferred.body":                    "'{{.listing_title}}' was handed over. Confirm receipt.",
	"order_transferred.title":                   "Equipment handed over",
	"org_admin_transfer_accepted.body":          "{{.to_user_name}} accepted the admin role of {{.organization_name}}.",
	"org_admin_transfer_accepted.title":         "Admin transfer accepted",
	"org_admin_transfer_cancelled.body":         "{{.from_user_name}} cancelled the admin transfer for {{.organization_name}}.",
	"org_admin_transfer_cancelled.title":        "Admin transfer cancelled",
	"org_admin_transfer_expired.body":           "The admin transfer for {{.organization_name}} with {{.counterparty_name}} expired without action.",
	"org_admin_transfer_expired.title":          "Admin transfer expired",
	"org_admin_transfer_initiated.body":         "{{.from_user_name}} wants to transfer the admin role of {{.organization_name}} to you. Respond before the offer expires.",
	"org_admin_transfer_initiated.title":        "Admin role transfer offer",
	"org_admin_transfer_rejected.body":          "{{.to_user_name}} declined the admin transfer for {{.organization_name}}.",
	"org_admin_transfer_rejected.title":         "Admin transfer declined",
	"org_admin_transferred_new.body":            "You have been made the admin of {{.tenant_name}}.",
	"org_admin_transferred_new.title":           "You are now the tenant admin",
	"org_admin_transferred_old.body":            "You transferred admin rights for {{.tenant_name}}.",
	"org_admin_transferred_old.title":           "Tenant admin transferred",
	"organisation_rejected.body":                "Your organization was rejected: {{.reason}}",
	"organisation_rejected.title":               "Organization rejected",
	"organisation_verified.body":                "{{.organization_name}} has been verified.",
	"organisation_verified.title":               "Organization verified",
	"tenant_invite_organisation_manager.body":   "{{.inviter_name}} invited you to join {{.tenant_name}} as a manager.",
	"tenant_invite_organisation_manager.title":  "Invitation to join {{.tenant_name}}",
	"tenant_invite_organisation_operator.body":  "{{.inviter_name}} invited you to join {{.tenant_name}} as an operator.",
	"tenant_invite_organisation_operator.title": "Invitation to join {{.tenant_name}}",
	"tenant_invite_personal_manager.body":       "{{.inviter_name}} invited you to {{.tenant_name}} as a manager.",
	"tenant_invite_personal_manager.title":      "Tenant invitation",
	"tenant_invite_personal_operator.body":      "{{.inviter_name}} invited you to {{.tenant_name}} as an operator.",
	"tenant_invite_personal_operator.title":     "Tenant invitation",
	"tenant_member_left.body":                   "{{.member_name}} is no longer a member of the tenant {{.tenant_name}}.",
	"tenant_member_left.title":                  "{{.member_name}} left the tenant",
	"tenant_member_removed_admin.body":          "{{.removed_member_name}} was removed from the tenant {{.tenant_name}}.",
	"tenant_member_removed_admin.title":         "{{.removed_member_name}} was removed from the tenant",
	"wallet_operation_decided.body":             "Your wallet operation for {{.amount}} {{.currency}} was {{.decision}}.",
	"wallet_operation_decided.title":            "Wallet operation {{.decision}}",
	"wallet_operation_requested.body":           "A {{.operation_kind}} of {{.amount}} {{.currency}} has been requested.",
	"wallet_operation_requested.title":          "Wallet operation requested",
}
