version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - bodyclose
    - revive
    - unconvert
    - goconst
    - gocyclo
    - gosec
    - misspell
