version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - bodyclose
    - revive
    - unconvert
    - goconst
    - gocyclo
    - gosec
    - misspell
    - forbidigo
  settings:
    forbidigo:
      forbid:
        - pattern: ^c\.JSON$
          pkg: ^github\.com/labstack/echo/v4\.Context$
          msg: "Use github.com/STECH-Super-App/go-common/pkg/response instead of direct c.JSON"
